version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
  groups:
    tailwind:
      patterns:
        - 'tailwindcss'
        - '@tailwindcss/*'
    vitest:
      patterns:
        - 'vitest'
        - '@vitest/*'
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
    day: "sunday"
    time: "00:00"
    timezone: "Europe/London"
  ignore:
    # Only send PRs for patch versions of Python.
    - dependency-name: "python"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
